Clean up and refactor project structure [#13]
opprop/universe pull request #16
Opened 2020-09-10 03:42 UTC by leoliu49

Addresses #13 

`GUT*` --> `Universe` (e.g. UniverseChecker)
`GUTI*` --> `UniverseTypeInference` (e.g. UniverseTypeInferenceChecker)

The same has been applied to tests.
I haven't made any functional changes, and I'm currently working on #15

2020-09-12 02:01 UTC, xingweitian reviewed
Thanks a lot for this PR!

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/lostyes/LostYes.java
> +package universe;
Should it be `typecheck.lostyes`?

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/strictpurity/Methods.java
> +package universe.strictpurity;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/ArrayVP.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/ArrayWF.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/Boxing.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/CallEquals.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/ComplexNew.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/lostno/LostNo.java
> +package typecheck.lostno;
Here you write `typecheck.lostno`, while other places you use `universe`. Please unify the uses.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/CondExpr.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/Defaults.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/FBound.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/GenericInterfaces.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/GenericInterfaces.java
> +package universe.topol;
I found that `GBounds.java` does not indicate the package, should we add a package statement to it?

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/Generics.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/GenericsArrays.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/MethodTypeVars.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/Wildcards.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/StaticVP.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/SimpleWF.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/SimpleVP.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/SimpleSub.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/SimpleNew.java
> +package universe.topol;
Same here.

2020-09-12 02:01 UTC, xingweitian commented on tests/typecheck/topol/Methods.java
> +package universe.topol;
Same here.

2020-09-12 17:18 UTC, leoliu49 commented on tests/typecheck/lostyes/LostYes.java
> +package universe;
Thanks for checking -- will fix for all the classes under `test`

2020-09-12 17:26 UTC, leoliu49 commented
Hi @xingweitian ! I've updated the tests to be consistent with `package typecheck.*`

2020-09-14 05:17 UTC, xingweitian approved these changes

2020-09-23 00:19 UTC, wmdietl requested changes
Thanks for this detailed work!
Can you do some more git magic to make it recognize that the test and VP files were moved and not deleted and added? For example, src/universe/UniverseViewpointAdaptor.java appears like a new file, but should be a renamed version of src/universe/GUTViewpointAdaptor.java. Same with a few test files.

I like the `GUT` to `Universe` renaming. For `GUTI`, the new name `UniverseTypeInference` is a bit odd. How about just `UniverseInference`?

2020-09-25 04:10 UTC, leoliu49 commented
> Can you do some more git magic to make it recognize that the test and VP files were moved and not deleted and added? For example, src/universe/UniverseViewpointAdaptor.java appears like a new file, but should be a renamed version of src/universe/GUTViewpointAdaptor.java. Same with a few test files.
> 

Hi Professor @wmdietl , `git` may not be recognizing some of the smaller renamings, and I'm having a little bit of trouble convincing them not to be delete + new file. I've tried separating the commits into a rename commit, then the actual refactoring, but tt seems that after squashing, `git` will just assume the files have been deleted-then-renamed anyway.
Is how it is right now okay?

2020-10-06 14:39 UTC, wmdietl approved these changes
Thanks for the renamings!

2020-10-06 14:39 UTC, merged