Cleanup scripts
opprop/universe pull request #31
Opened 2021-12-16 22:51 UTC by piyush-J

2022-01-13 22:06 UTC, piyush-J commented on scripts/infer_v2.sh
> +#!/bin/bash
Delete this file

2022-01-13 22:08 UTC, piyush-J commented on scripts/run-dljc.sh
> +export CLASSPATH="$JSR308"/universe/bin/src:$CHECKERFRAMEWORK/dataflow/build:$CHECKERFRAMEWORK/javacutil/build:$CHECKERFRAMEWORK/stubparser/build:$CHECKERFRAMEWORK/framework/build:$CHECKERFRAMEWORK/c
Use steup.sh instead of this duplication

2022-01-17 00:09 UTC, wmdietl requested changes

2022-01-17 00:09 UTC, wmdietl commented on scripts/setup.sh
> +# Playground top level directory
```suggestion
# Universe top level directory
```

2022-01-17 00:09 UTC, wmdietl commented on scripts/setup.sh
> +export CLASSPATH="$UNIVERSE"/bin/src:$CHECKERFRAMEWORK/dataflow/build:$CHECKERFRAMEWORK/javacutil/build:$CHECKERFRAMEWORK/stubparser/build:$CHECKERFRAMEWORK/framework/build:$CHECKERFRAMEWORK/checker/
I think several of these entries can be removed.
- `"$UNIVERSE"/bin/src` is odd. What is in the `bin/src` directory that should be on the classpath? I think `bin` used to be the output directory of Eclipse. I don't think it needs to be added.
- The `build` directories are probably not correct: the class files are further down in the hierarchies. This needs to either be updated or we remove these and just require the .jar files be built.
- are the junit and hamcrest class files not contained in `checker-framework-inference.jar`? I assume the latter contains everything from `checker.jar`, but maybe not these test files.

2022-01-19 19:51 UTC, wmdietl reviewed
Thanks! A few small comments left.

2022-01-19 19:51 UTC, wmdietl commented on scripts/check.sh
> +set -e
For consistency, should we add this to all scripts to quit on errors?
(Also, line 3 was removed or is absent in other files, so could be removed here, too)

2022-01-19 19:51 UTC, wmdietl commented on scripts/debug.sh
> +#!/bin/bash
Maybe `debug-infer.sh` would be a better name for this script?

2022-01-19 19:51 UTC, wmdietl commented on scripts/run-dljc.sh
> +JSR308=$JSR308
This variable isn't used in other scripts and isn't set in setup.sh.
Can you please remove it and just do it relative to `MYDIR`, like it's done in other scripts?

2022-01-19 19:51 UTC, wmdietl commented on scripts/setup.sh
> +export CLASSPATH=$CFI/bin:$CFI/dist/org.ow2.sat4j.core-2.3.4.jar:$CFI/dist/commons-logging-1.2.jar:$CFI/dist/log4j-1.2.16.jar:./build/libs/universe.jar:$CFI/dist/checker-framework-inference.jar:$CLAS
Does `$CFI/bin` contain compiled `.class` files? I think we should remove this and, if at all, add the directories where gradle puts its output.

2022-01-21 23:56 UTC, wmdietl approved these changes

2022-01-21 23:56 UTC, merged