Update preliminary project structure and build files
opprop/universe pull request #9
Opened 2020-07-09 18:41 UTC by leoliu49

Prof. Dietl suggested I break up PR https://github.com/opprop/universe/pull/3 into smaller chunks.
For this part, I cherrypicked commits so that the build and configuration files are set appropriately.

Next steps:
1. Make a separate PR for project file organization refactoring
2. Apply remainder of the commits in https://github.com/opprop/universe/pull/3

2020-07-23 22:41 UTC, wmdietl requested changes
@leoliu49 Thanks for working on breaking down this large PR! I have lots of small comments that would be great to look into.
Maybe it would make sense to further break this down into smaller PRs:
- remove Eclipse files,
- update version control files,
- move test files,
- etc...

That will make the PRs easier to review and the history cleaner.

2020-07-23 22:41 UTC, wmdietl commented on build.gradle
> +def jreVersion  = {
@xingweitian @leoliu49 Can you have a look through the build.gradle and make it consistent with the current CFI build style?

2020-07-23 22:41 UTC, wmdietl commented on build.gradle
> +    compile group: 'junit', name: 'junit', version: '4.12'
I would use one consistent style, so either the `x:y:z` style or the `group: x, name: y, version: z` style.

2020-07-23 22:41 UTC, wmdietl commented on build.gradle
> +  if(jreVersion == 1.7) {
We no longer support java 7, so special casing that can be removed.
Instead, we need to special case Java 8 and use the error-prone compiler if necessary.

2020-07-23 22:41 UTC, wmdietl commented on scripts/env-setup.sh
> +#!/bin/bash
Could you also add a top-level README.md file that gives an overview of all the different scripts and when to use them?

2020-07-23 22:41 UTC, wmdietl commented on scripts/env-setup.sh
> +export JSR308=$(cd $(dirname "$0")/../.. && pwd)
Make sure that no file has the "No newline at EOF" warning sign.

2020-07-23 22:41 UTC, wmdietl commented on scripts/projects-setup.sh
> +if [ -d $JSR308/generic-type-inference-solver ] ; then
This project is dead and we shouldn't have to clone it.

2020-07-23 22:41 UTC, wmdietl commented on scripts/projects-setup.sh
> +    (cd $JSR308 && git clone -b hackathon --depth 1 https://github.com/"$REPO_SITE"/checker-framework-inference.git)
Is it enough to clone this project and then call `gradlew cloneAndBuildDependencies` in that project?
https://github.com/opprop/checker-framework-inference/blob/master/build.gradle#L249

2020-07-23 22:41 UTC, wmdietl commented on scripts/projects-setup.sh
> +ant -f $JSR308/checker-framework/checker/build.xml jar
These build commands also look out-of-date.

2020-07-23 22:41 UTC, wmdietl commented on src/GUT/GUTAnnotatedTypeFactory.java
> +    public AnnotatedTypeMirror getAnnotatedType(Element elt) {
There is no point in overriding a method and then only calling super.

2020-07-23 22:41 UTC, wmdietl commented on src/GUT/GUTVisitor.java
> + * Type visitor to enforce the gut type rules.
The upper-case `GUT` seems easier to read to me.

2020-07-23 22:41 UTC, wmdietl commented on src/GUT/GUTVisitor.java
> +                    //checker.report(Result.failure("uts.receiver.annotations.forbidden"),node);
There at least needs to be a TODO here why the error is disabled.

2020-07-23 22:41 UTC, wmdietl commented on src/GUTI/GUTIAnnotatedTypeFactory.java
> +/*    @Override
Let's not add debugging artifacts like this one.

2020-07-23 22:41 UTC, wmdietl commented on src/GUTI/GUTIAnnotatedTypeFactory.java
> +        GUTAnnotatedTypeFactory gutATF = (GUTAnnotatedTypeFactory) realTypeFactory;
The try-block here is really ugly. Can you see whether this actually still crashes?
Add a big TODO that this should be cleaned up.
I'm not sure whether we need to create an equality constraint here. Maybe the old implementation was good enough?

2020-07-23 22:41 UTC, wmdietl commented on src/GUTI/GUTIAnnotatedTypeFactory.java
> +                cm.addInequalityConstraint(sm.getVariableSlot(atm), sm.getSlot(gutATF.BOTTOM));
I would also put `sm.getVariableSlot(atm)` into a local variable.

2020-07-23 22:41 UTC, wmdietl commented on src/GUTI/GUTIAnnotatedTypeFactory.java
> +                cm.addInequalityConstraint(sm.getVariableSlot(atm), sm.getSlot(gutATF.ANY));
I'm not sure why ANY should be forbidden for a cast type.

2020-07-23 22:41 UTC, wmdietl commented on src/GUTI/GUTIChecker.java
> +        return true;
I think we don't want this - local variables should be top and then refined automatically.

2020-07-23 22:41 UTC, wmdietl commented on src/GUTI/GUTIMaxSatSerializer.java
> +                /*for (int i=0; i<resultClauses.length; i++) {
Don't add debugging code like this.

2020-07-23 22:41 UTC, wmdietl commented on src/GUTI/GUTIVisitor.java
> + * Type visitor to either enforce or infer the gut type rules.
Throughout these changes, don't change `GUT` to `gut`.

2020-07-23 22:41 UTC, wmdietl commented on src/GUTI/GUTIVisitor.java
> +        //return new GUTIInferenceValidator(checker, this, atypeFactory);
I don't see a point in this change.

2020-07-23 22:41 UTC, wmdietl commented on tests/GUTI/TypeVariableUse.java
> -import GUT.qual.*;
Why do a few changes appear as removed-adds instead of as moves?

2020-07-23 22:41 UTC, wmdietl commented on tst/GUT/GUTTestsLostNo.java
> +import java.io.File;
Is `tst` the best name for this directory?

2020-08-24 08:19 UTC, xingweitian commented on build.gradle
> +def jreVersion  = {
Just found this comment...
I made the change in another branch before: https://github.com/opprop/universe/blob/adapt-to-cf-master/build.gradle

2020-08-24 08:20 UTC, xingweitian commented on build.gradle
> +def jreVersion  = {
This PR should merge with the branch `adapt-to-cf-master`. We used to work on that one.

2020-08-29 01:49 UTC, closed without merging